module BattleSoup.Nucleus

open System.Drawing
open BattleSoup.Util
open BattleSoup.Geometry
open BattleSoup.Drawing
open BattleSoup.Sprite
open BattleSoup.Visual
open BattleSoup.Atom

/// A type of nucleus atom, a large active atom that can move other atoms in a certain distance within it.
type NucleusType (level : int) =
    inherit AtomType (10.0, 30.0, 0.2)

    override this.GetVisual atom = Visual.Null
    
    /// Gets the maximum force generated by the nucleus when moving atoms.
    member this.MoveForce = 50.0 + float level * 25.0

    /// Gets the maximum radius in which the nucleus can move atoms.
    member this.MoveRadius = 100.0 + sqrt (float level) * 25.0